language: r
r: devel
sudo: TRUE


bioc_packages:
  - BiocStyle

r_packages:
  - rstan

notifications:
  email: TRUE

cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes', '--log temp.log'
r_check_args: '--ignore-vignettes'


before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars


after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
