language: r
r: bioc-devel
sudo: TRUE

os: linux
#   - linux
#  - windows
#  - osx


repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org


notifications:
  email: TRUE


cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

script:
  - R CMD build . >> log_build.log
  - R CMD check IgGeneUsage_0.99.0.tar.gz >> log_build_check.log

before_install:
  - R -q -e 'install.packages(c("rstan"))'
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check IgGeneUsage*tar.gz

after_script:
  - tar -ztvf rstanarm_*.tar.gz

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat IgGeneUsage.Rcheck/00*
